version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:3.7.8 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
        - name: Flake8 tests
          - command: |
              pip install flake8 flake8-junit-report
              mkdir test
              mkdir test/flake8
              flake8 src/ --output-file=test/flake8/report.txt
              flake8_junit test/flake8/report.txt test/flake8/report.xml
      - store_test_results:
          path: test/flake8
      - store_artifacts:
          path: test/flake8
