version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:3.7.8 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Flake8 Code Quality
          command: |
            pip install flake8 flake8-junit-report
            mkdir test_logs
            mkdir test_logs/flake8
            flake8 src/ --output-file=test_logs/flake8/report.txt --exit-zero
            flake8_junit test_logs/flake8/report.txt \
              test_logs/flake8/report.xml
            flake8 src/
      - store_test_results:
          path: test_logs/flake8
      - store_artifacts:
          path: test_logs/flake8
      - run:
          name: Pytest Unit Tests
          command: |
            mkdir test_logs/pytest
            pytest --import-mode=prepend \
              --junit-xml=test_logs/pytest/report.xml \
              --verbose > test_logs/pytest/report.txt
      - store_test_results:
          path: test_logs/pytest
      - store_artifacts:
          path: test_logs/pytest
