version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:3.7.8 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Flake8 tests
          command: |
            pip install flake8 flake8-junit-report
            mkdir test_logs
            mkdir test_logs/flake8
            flake8 src/ --output-file=test_logs/flake8/report.txt \
            ; cat test_logs/flake8/report.txt
      - store_test_results:
          path: test_logs/flake8
      - store_artifacts:
          path: test_logs/flake8
